###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '8081:8025'

    redis:
        image: 'redis:alpine'

    postgres:
        image: 'postgres:15-alpine'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=9101721
            - POSTGRES_DB=news_app_db
        ports:
            - '8084:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
